# Generated by Django 3.2.22 on 2024-03-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovtEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
                ('pre_event_image', models.ImageField(upload_to='images')),
                ('mid_event_image', models.ImageField(upload_to='images')),
                ('post_event_image', models.ImageField(upload_to='images')),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.assemblycategory')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.parliamentcategory')),
            ],
        ),
    ]
