# Generated by Django 5.0.3 on 2024-03-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblycategory',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parliamentcategory',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
